// import TourDetail from "../views/tourDetail";
const TourData = [
  {
    id: "1",
    title: "6D/4N Fun Tassie Vacation ...",
    fTitle: "6D/4N Fun Tassie Vacation + Sydney",
    price: "12,398,000",
    place: "Australia",
    pages: "12/15",
    acomodation: "Hotel 4 Night",
    transportation: "Qatar Airways",
    eat: "Included as Itinerary",
    duration: "6 days 4 night",
    dateTrip: "26 August 2020",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, labore. Tempora sunt doloremque officiis adipisci. Nam iusto, doloremque beatae unde dignissimos voluptatem nesciunt dolore aut consectetur sequi? Ipsam, in iste corrupti hic laborum non aperiam, nihil delectus error esse consequatur, consequuntur voluptatibus natus officia deleniti eligendi incidunt dolor reprehenderit facilis.",
  },
  {
    id: "2",
    title: "6D/4N Exciting Summer in ...",
    fTitle: "6D/4N Exciting Summer",
    price: "12,398,000",
    place: "Australia",
    pages: "12/15",
    acomodation: "Hotel 4 Night",
    transportation: "Qatar Airways",
    eat: "Included as Itinerary",
    duration: "6 days 4 night",
    dateTrip: "26 August 2020",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, labore. Tempora sunt doloremque officiis adipisci. Nam iusto, doloremque beatae unde dignissimos voluptatem nesciunt dolore aut consectetur sequi? Ipsam, in iste corrupti hic laborum non aperiam, nihil delectus error esse consequatur, consequuntur voluptatibus natus officia deleniti eligendi incidunt dolor reprehenderit facilis.",
  },
  {
    id: "3",
    title: "8D/6N Wonderful Autum ...",
    fTitle: "8D/6N Wonderful Autum",
    price: "12,398,000",
    place: "Australia",
    pages: "12/15",
    acomodation: "Hotel 4 Night",
    transportation: "Qatar Airways",
    eat: "Included as Itinerary",
    duration: "6 days 4 night",
    dateTrip: "26 August 2020",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, labore. Tempora sunt doloremque officiis adipisci. Nam iusto, doloremque beatae unde dignissimos voluptatem nesciunt dolore aut consectetur sequi? Ipsam, in iste corrupti hic laborum non aperiam, nihil delectus error esse consequatur, consequuntur voluptatibus natus officia deleniti eligendi incidunt dolor reprehenderit facilis.",
  },
  {
    id: "4",
    title: "4D/3N Overland Jakarta B...",
    fTitle: "4D/3N Overland Jakarta",
    price: "12,398,000",
    place: "Australia",
    pages: "12/15",
    acomodation: "Hotel 4 Night",
    transportation: "Qatar Airways",
    eat: "Included as Itinerary",
    duration: "6 days 4 night",
    dateTrip: "26 August 2020",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, labore. Tempora sunt doloremque officiis adipisci. Nam iusto, doloremque beatae unde dignissimos voluptatem nesciunt dolore aut consectetur sequi? Ipsam, in iste corrupti hic laborum non aperiam, nihil delectus error esse consequatur, consequuntur voluptatibus natus officia deleniti eligendi incidunt dolor reprehenderit facilis.",
  },
  {
    id: "5",
    title: "4D/3N Labuan Bajo Delight",
    fTitle: "4D/3N Labuan Bajo Delight",
    price: "12,398,000",
    place: "Australia",
    pages: "12/15",
    acomodation: "Hotel 4 Night",
    transportation: "Qatar Airways",
    eat: "Included as Itinerary",
    duration: "6 days 4 night",
    dateTrip: "26 August 2020",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, labore. Tempora sunt doloremque officiis adipisci. Nam iusto, doloremque beatae unde dignissimos voluptatem nesciunt dolore aut consectetur sequi? Ipsam, in iste corrupti hic laborum non aperiam, nihil delectus error esse consequatur, consequuntur voluptatibus natus officia deleniti eligendi incidunt dolor reprehenderit facilis.",
  },
  {
    id: "6",
    title: "5D/4N Magic Tokyo Fun",
    fTitle: "5D/4N Magic Tokyo Fun",
    price: "12,398,000",
    place: "Australia",
    pages: "12/15",
    acomodation: "Hotel 4 Night",
    transportation: "Qatar Airways",
    eat: "Included as Itinerary",
    duration: "6 days 4 night",
    dateTrip: "26 August 2020",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, labore. Tempora sunt doloremque officiis adipisci. Nam iusto, doloremque beatae unde dignissimos voluptatem nesciunt dolore aut consectetur sequi? Ipsam, in iste corrupti hic laborum non aperiam, nihil delectus error esse consequatur, consequuntur voluptatibus natus officia deleniti eligendi incidunt dolor reprehenderit facilis.",
  },
];


export default TourData;
